In [1]:
import pandas as pd
import numpy as np
import matplotlib
import random

In [3]:
# Create an array containing 10 random numbers ranging from 0 to 1.(创建一个包含10个随机数的数组，数值范围在0-1之间)
random_array = np.random.random(10)
print(random_array)

[0.84470978 0.67905733 0.3956157  0.08384221 0.69791927 0.12110152
 0.16062789 0.48560825 0.17297602 0.0030096 ]


In [5]:
# Create a 3x3 matrix containing the numbers 1 to 9.(创建一个3x3的矩阵，包含数字1-9)
list5=[[1,2,3],[4,5,6],[7,8,9]]
c = np.array(list5)
print(c)
print(type(c))

#method2
matrix = np.array([[1,2,3],[1,2,3],[1,2,3]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [7]:
# Create an array from 0 to 10 with a step size of 0.5.(创建一个从0到10，步长为0.5的数组)
num3 = np.arange(0,10.5,0.5)
print(num3)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [17]:
# # Given an array of stock prices： prices = [100, 102, 105, 103, 108]
stock_array = np.array([100, 102, 105, 103, 108])

# Calculate daily returns (price on the next day / price on the previous day - 1)
returns = stock_array[1:]/stock_array[0:-1] -1
print("stock_array: {}\nreturns:{}".format(stock_array,returns))

# Calculate the average price and the standard deviation of prices
avg_prices = np.mean(stock_array)
std_prices = np.std(stock_array)
print(f"Average Price: {avg_prices:.2f}, Standard deviation: {std_prices:.2f}")

# Find the highest price and its corresponding index position
p_max=np.max(stock_array)
max_index = np.argmax(stock_array)
print(p_max,max_index)

stock_array: [100 102 105 103 108]
returns:[ 0.02        0.02941176 -0.01904762  0.04854369]
Average Price: 103.60, Standard deviation: 2.73
108 4


In [11]:
# Given a set of investment returns: returns = [0.02, -0.01, 0.03, 0.015, -0.005] 
# 给定一组投资收益率：returns = [0.02, -0.01, 0.03, 0.015, -0.005]
returns_array = np.array([0.02, -0.01, 0.03, 0.015, -0.005])

# Calculate cumulative return
# 计算累积收益率
cumulative_return = np.prod(1+returns_array) -1

# Calculate annualized return (assuming 252 trading days)
# 计算年化收益率（假设252个交易日）
annual_r = (1+cumulative_return)**(252/5) -1
print("Returns Array: {}\nCumulative Return: {:.2f}\nAnnual Returns: {:.2f}".format(returns_array,cumulative_return,annual_r))

# Calculate maximum drawdown
# 最大回撤
cumulative = np.cumprod(1 + returns)
running_max = np.maximum.accumulate(cumulative)
drawdown = (cumulative - running_max) / running_max
max_drawdown = np.min(drawdown)
print(f"Maximum Drawdown: {max_drawdown:.4f}")

Returns Array: [ 0.02  -0.01   0.03   0.015 -0.005]
Cumulative Return: 0.05
Annual Returns: 10.93
Maximum Drawdown: -0.0190


In [13]:
# Create a return matrix for three assets (5 days of data)
# Asset A: [0.01, 0.02, -0.01, 0.03, 0.015]
# Asset B: [0.015, 0.018, 0.005, 0.025, 0.01]
# Asset C: [0.008, 0.022, -0.005, 0.028, 0.012]
# Calculate the covariance matrix
# Calculate the variance of each asset
# Calculate the correlation coefficient matrix
P = np.array([[0.01, 0.02, -0.01, 0.03, 0.015],[0.015, 0.018, 0.005, 0.025, 0.01],[0.008, 0.022, -0.005, 0.028, 0.012]])
cov = np.cov(P,rowvar =True)
var = np.var(P,axis=1)
corr_matrix = np.corrcoef(P)
print(f"Portfolio:\n{P}")
print("Covariance:\n{}\nVariance:\n{}\nCorrelation:\n{}".format(cov,var,corr_matrix))

Portfolio:
[[ 0.01   0.02  -0.01   0.03   0.015]
 [ 0.015  0.018  0.005  0.025  0.01 ]
 [ 0.008  0.022 -0.005  0.028  0.012]]
Covariance:
[[2.2000e-04 1.0275e-04 1.8625e-04]
 [1.0275e-04 5.8300e-05 9.0500e-05]
 [1.8625e-04 9.0500e-05 1.6400e-04]]
Variance:
[1.760e-04 4.664e-05 1.312e-04]
Correlation:
[[1.         0.90726929 0.98053481]
 [0.90726929 1.         0.925534  ]
 [0.98053481 0.925534   1.        ]]
