In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create a DataFrame containing the following data:
# Date: from 2024-01-01 to 2024-01-05
# Stock symbols: ['AAPL', 'GOOGL', 'MSFT', 'AAPL', 'GOOGL']
# Prices: [150, 2800, 340, 152, 2820]
# Trading volumes: [1000000, 500000, 800000, 1200000, 450000]

Data = {"Date": pd.date_range('2024-01-01','2024-01-05'),
        "Stock":['AAPL', 'GOOGL', 'MSFT', 'AAPL', 'GOOGL'],
        "Price":[150, 2800, 340, 152, 2820],
        "Volumes":[1000000, 500000, 800000, 1200000, 450000]}
df=pd.DataFrame(Data)
print(df)

        Date  Stock  Price  Volumes
0 2024-01-01   AAPL    150  1000000
1 2024-01-02  GOOGL   2800   500000
2 2024-01-03   MSFT    340   800000
3 2024-01-04   AAPL    152  1200000
4 2024-01-05  GOOGL   2820   450000


In [3]:
#Q1:
# # Filter and extract all records for AAPL stock（筛选出AAPL股票的数据）
aapl = df[df['Stock'] == 'AAPL']
print(aapl)
print()

# Calculate the average price and total trading volume for each stock（计算每只股票的平均价格和总交易量）
stock_summary = df.groupby('Stock').agg(
    avg_price=('Price', 'mean'),
    total_volumes=('Volumes', 'sum')
)
avg_price_by_stock = df.groupby('Stock')['Price'].mean()
total_volume_by_stock = df.groupby('Stock')['Volumes'].sum()
print(stock_summary)
print()

# Find all stock records with prices greater than 200（找出价格大于200的所有股票记录）
price_larger200 = df[df["Price"]>200]
print(price_larger200)

        Date Stock  Price  Volumes
0 2024-01-01  AAPL    150  1000000
3 2024-01-04  AAPL    152  1200000

       avg_price  total_volumes
Stock                          
AAPL       151.0        2200000
GOOGL     2810.0         950000
MSFT       340.0         800000

        Date  Stock  Price  Volumes
1 2024-01-02  GOOGL   2800   500000
2 2024-01-03   MSFT    340   800000
4 2024-01-05  GOOGL   2820   450000


In [7]:
#Q2:
# Create stock price data for 5 consecutive trading days（创建连续5个交易日的股价数据）
stock1_price_data = [[150,155,149,152],
                   [152,158,150,154],
                   [154,160,152,159],
                   [159,162,153,154],
                   [154,155,147,152]]

stock1_df = pd.DataFrame(stock1_price_data, columns=("Open","High","Low","Close"))
stock1_df["Date"] = pd.date_range("2024-01-01","2024-01-05")
stock1_df = stock1_df.set_index("Date")
print(stock1_df,"\n")

# Calculate the 5-day moving average of the closing price（计算5日移动平均价格）
MA_5 = stock1_df['Close'].rolling(window=5).mean()
print(f"5-day Moving Average:{MA_5}\n")

# Calculate daily price range (High - Low), Assuming daily data includes: Open, High, Low, Close
# 计算每日价格波动（最高-最低），假设每日数据为：[开盘, 最高, 最低, 收盘]
stock1_df["Daily Price Change"]= stock1_df['High']-stock1_df["Low"]
print(stock1_df,"\n")

            Open  High  Low  Close
Date                              
2024-01-01   150   155  149    152
2024-01-02   152   158  150    154
2024-01-03   154   160  152    159
2024-01-04   159   162  153    154
2024-01-05   154   155  147    152 

5-day Moving Average:Date
2024-01-01      NaN
2024-01-02      NaN
2024-01-03      NaN
2024-01-04      NaN
2024-01-05    154.2
Name: Close, dtype: float64

            Open  High  Low  Close  Daily Price Change
Date                                                  
2024-01-01   150   155  149    152                   6
2024-01-02   152   158  150    154                   8
2024-01-03   154   160  152    159                   8
2024-01-04   159   162  153    154                   9
2024-01-05   154   155  147    152                   8 



In [9]:
# # Create more detailed stock price data 创建更详细的股价数据
np.random.seed(42)
dates = pd.date_range('2024-01-01', periods=10)
stock_data = []

for i in range(10):
    base_price = 100 + i * 2
    high = base_price + np.random.uniform(1, 3)
    low = base_price - np.random.uniform(1, 3)
    close = np.random.uniform(low, high)
    
    stock_data.append({
        'date': dates[i],
        'open': base_price,
        'high': high,
        'low': low,
        'close': close
    })

price_df = pd.DataFrame(stock_data)
price_df.set_index('date', inplace=True)

#  Calculate the moving average 计算移动平均
price_df['5_day_MA'] = price_df['close'].rolling(window=5).mean()

# Calculate daily price range 计算价格波动
price_df['daily_range'] = price_df['high'] - price_df['low']

print("Stock price data and indicators:")
print(price_df.round(2))

Stock price data and indicators:
            open    high     low   close  5_day_MA  daily_range
date                                                           
2024-01-01   100  101.75   97.10  100.50       NaN         4.65
2024-01-02   102  104.20  100.69  101.24       NaN         3.51
2024-01-03   104  105.12  101.27  103.58       NaN         3.85
2024-01-04   106  108.42  104.96  108.31       NaN         3.46
2024-01-05   108  110.66  106.58  107.32    104.19         4.09
2024-01-06   110  111.37  108.39  109.95    106.08         2.98
2024-01-07   112  113.86  110.42  112.53    108.34         3.45
2024-01-08   114  115.28  112.42  113.46    110.31         2.86
2024-01-09   116  117.91  113.43  114.32    111.52         4.48
2024-01-10   118  120.03  115.82  116.01    113.26         4.21


In [11]:
#Q3:
# Create a financial DataFrame with missing values（创建一个包含缺失值的金融DataFrame）
# Fill missing values using appropriate methods（使用适当的方法填充缺失值）
# Detect and handle outliers (prices beyond 3 standard deviations) 检测并处理异常值（价格超过3个标准差）
data_with_null = [[150,155,149,152],
                   [152,158,None,154],
                   [154,160,152,159],
                   [159,"",153,154],
                   [154,155,140,1520]]
null_df = pd.DataFrame(data_with_null,columns=["Open","High","Low","Close"])
date2 = pd.date_range("2024-01-01","2024-01-05")
null_df["Date"] = date2
null_df = null_df.set_index("Date") 
print("DateFrame with null:\n{}\n".format(null_df))

#Convert empty strings ("") to NaN
null_df.replace("", np.nan, inplace=True)
print("Convert empty strings ("") to NaN:\n",null_df,"\n")

#Convert all numeric columns to numbers
null_df = null_df.astype(float)

#Fill missing values using the column mean
null_df.fillna(null_df.mean(),inplace = True)
print("Fill missing values using the column mean:\n",null_df,'\n')

# Outliers: values greater than mean ± 3*std
price_cols = ["Open", "High", "Low", "Close"]

for col in price_cols:
    col_mean = null_df[col].mean()
    col_std = null_df[col].std()

    null_df[f"{col}_is_outlier"] = (
        abs(null_df[col] - col_mean) > 3 * col_std
    )

print("Outlier detection results for all price columns:\n", null_df)

DateFrame with null:
            Open High    Low  Close
Date                               
2024-01-01   150  155  149.0    152
2024-01-02   152  158    NaN    154
2024-01-03   154  160  152.0    159
2024-01-04   159       153.0    154
2024-01-05   154  155  140.0   1520

Convert empty strings () to NaN:
             Open   High    Low  Close
Date                                 
2024-01-01   150  155.0  149.0    152
2024-01-02   152  158.0    NaN    154
2024-01-03   154  160.0  152.0    159
2024-01-04   159    NaN  153.0    154
2024-01-05   154  155.0  140.0   1520 

Fill missing values using the column mean:
              Open   High    Low   Close
Date                                   
2024-01-01  150.0  155.0  149.0   152.0
2024-01-02  152.0  158.0  148.5   154.0
2024-01-03  154.0  160.0  152.0   159.0
2024-01-04  159.0  157.0  153.0   154.0
2024-01-05  154.0  155.0  140.0  1520.0 

Outlier detection results for all price columns:
              Open   High    Low   Close  Open_is

In [13]:
#Q4:
# Create data containing multiple stocks across multiple trading days 创建包含多个股票多个交易日的数据
data4={"Date":pd.date_range("2024-01-01","2024-01-06").tolist()*3,
      "Stock":['AAPL']*6 + ['GOOGL']*6 + ['MSFT']*6,
       "Price":[150,152,153,155,154,156,
              2800,2820,2810,2830,2840,2850,
              330,335,332,338,336,340],
       "Volumes":[1_000_000,1_200_000,1_050_000,1_300_000,1_250_000,1_100_000,
               500_000,520_000,480_000,600_000,590_000,610_000,
               800_000,820_000,810_000,830_000,850_000,900_000]}
df4 = pd.DataFrame(data4)
print(df4,"\n")

# Calculate price volatility (standard deviation) by stock 按股票分组计算波动率(std)
group = df4.groupby("Stock")["Price"].std()
print(group,"\n")

# Calculate total market trading volume for each trading day 计算每个交易日的市场总交易量
total_volumes = df4.groupby('Date')['Volumes'].sum()
print("total_volumes:\n",total_volumes,"\n")

# Identify trading days with unusually high trading volume--volume greater than mean + 2 * standard deviation
# 找出交易量突增的交易日, 超过均值 + 2 * 标准差
mean_vol = total_volumes.mean()
std_vol = total_volumes.std()
threshold = mean_vol + 2*std_vol
spike_day = total_volumes > threshold
print(spike_day)

         Date  Stock  Price  Volumes
0  2024-01-01   AAPL    150  1000000
1  2024-01-02   AAPL    152  1200000
2  2024-01-03   AAPL    153  1050000
3  2024-01-04   AAPL    155  1300000
4  2024-01-05   AAPL    154  1250000
5  2024-01-06   AAPL    156  1100000
6  2024-01-01  GOOGL   2800   500000
7  2024-01-02  GOOGL   2820   520000
8  2024-01-03  GOOGL   2810   480000
9  2024-01-04  GOOGL   2830   600000
10 2024-01-05  GOOGL   2840   590000
11 2024-01-06  GOOGL   2850   610000
12 2024-01-01   MSFT    330   800000
13 2024-01-02   MSFT    335   820000
14 2024-01-03   MSFT    332   810000
15 2024-01-04   MSFT    338   830000
16 2024-01-05   MSFT    336   850000
17 2024-01-06   MSFT    340   900000 

Stock
AAPL      2.160247
GOOGL    18.708287
MSFT      3.710346
Name: Price, dtype: float64 

total_volumes:
 Date
2024-01-01    2300000
2024-01-02    2540000
2024-01-03    2340000
2024-01-04    2730000
2024-01-05    2690000
2024-01-06    2610000
Name: Volumes, dtype: int64 

Date
2024-01-01    

In [15]:
# 1. Calculate daily returns for each stock 计算每只股票的每日收益率
# 2. Calculate portfolio returns (assuming equal-weighted investment) 计算投资组合收益率（假设等权重投资）
# 3. Calculate cumulative portfolio returns 计算投资组合的累积收益
stock_prices = np.array([
    [100, 102, 101, 105, 108],  # 股票A
    [50, 52, 51, 55, 53],       # 股票B
    [200, 201, 205, 202, 210]   # 股票C
])
returns = stock_prices[:, 1:] / stock_prices[:, :-1] - 1

portfolio_r = np.mean(returns,axis=0)
cum_r = np.cumprod(1+portfolio_r) -1
print("returns:\n",returns)
print("portofolio returns:\n",portfolio_r,"\ncumulative returns:\n",cum_r)
# 4. Identify the stock with the highest return 找出收益最好的股
total_returns = stock_prices[:,-1]/stock_prices[:,0]-1
print("total returns of each stock:\n",total_returns)
best_index = np.argmax(total_returns)
print("the stock index with the highest return is:\n",best_index)

returns:
 [[ 0.02       -0.00980392  0.03960396  0.02857143]
 [ 0.04       -0.01923077  0.07843137 -0.03636364]
 [ 0.005       0.0199005  -0.01463415  0.03960396]]
portofolio returns:
 [ 0.02166667 -0.00304473  0.03446706  0.01060392] 
cumulative returns:
 [0.02166667 0.01855597 0.0536626  0.06483555]
total returns of each stock:
 [0.08 0.06 0.05]
the stock index with the highest return is:
 0


In [17]:
# Calculate the annualized volatility of each stock (assuming 252 trading days) 计算每只股票的年化波动率（假设252个交易日）
# Calculate the variance-covariance matrix of the portfolio 计算投资组合的方差-协方差矩阵
# Calculate the annualized volatility of the portfolio 计算投资组合的年化波动率

std_return = np.std(returns,axis=1)
annual_vol =  std_return * np.sqrt(252)
print("annualized volatility of each stock is:\n",annual_vol)
cov_matrix =np.cov(returns)
print("variance-covariance matrix of the portfolio is:\n",cov_matrix)
# portfolio volatility (equal-weighted portfolio) 投资组合波动率（等权重）
weights = np.array([1/3, 1/3, 1/3])
portfolio_variance = weights @ cov_matrix @ weights.T
portfolio_volatility = np.sqrt(portfolio_variance) * np.sqrt(252)
print(portfolio_volatility)

annualized volatility of each stock is:
 [0.29113555 0.72990357 0.31568922]
variance-covariance matrix of the portfolio is:
 [[ 0.00044847  0.0006082  -0.00017341]
 [ 0.0006082   0.00281883 -0.00118468]
 [-0.00017341 -0.00118468  0.0005273 ]]
0.2534855232497369
